language: node_js
node_js:
  - "0.12.1"

addons:
  code_climate:
    repo_token: cc2b7264e6f629ae268c6ed2f0959fb8cecc8e1a6f6e4dd2e4247a379a1c0ec5

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_script:
  - codeclimate-test-reporter < coverage/**/lcov.info

env:
  - TEST_SCOPE=angular_1.4.x

notifications:
  webhooks: https://webhooks.gitter.im/e/b3fad143b541daf56e89
